version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USERNAME: postgres	
      POSTGRES_PASSWORD: ecrnow@2024
      POSTGRES_DB: ecrnow
    #networks:
    #  - ecrnow_network
    ports:
      - "5432:5432"
